MACROBLOCK_SIZE = 16
BLOCK_Y_SIZE = 8
RAYON = 2
SEQUENCE_LEN = 15

# Fraction de pixel soit 1/2
INCREMENT = 1

MACROBLOCK_THRESHOLD = 256
BLOCK_Y_THRESHOLD = 64

PLOT_HEAT_MAP = False
RESULT_FILE_PATH = "./result.csv"
